apiVersion: v1
kind: Service
metadata:
  name: user-profile-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: user-profile-service
  ports:
    - port: {{ .Values.userProfileService.port }}
      targetPort: {{ .Values.userProfileService.port }}
  type: ClusterIP