version: '3.9'

services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  user-profile-service:
    image: user-profile-service
    container_name: user-profile-service
    restart: unless-stopped
    ports:
      - "9001:9001"
    depends_on:
      - mongodb
    environment:
      SPRING_MONGODB_URI: mongodb://admin:password@mongodb:27017/user-profiles?authSource=admin